server:
  port: 8781

#指定服务中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: order-service
  #整合redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000ms
  zipkin:
    base-url: http://localhost:9411

#自定义负载均衡策略
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#设置feign超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
  hystrix:
    enabled: true

#设置hystrix超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

#hystrix-dashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"


